version: '3.9'

services:
  node:
    container_name: service-driver-pay
    ports:
      - 3001:3001
    build: .
    command: npm start
    volumes:
      - .:/usr/src/back-driver-pay-service
  db:
    image: mongo
    container_name: mongo-driver-pay
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null